---
packages_debian_default:
  [
  unattended-upgrades,
  acl,
  git,
  vim,
  curl,
  wget,
  zsh,
  mosh,
  tmux,
  rsync,
  htop,
  nmap,
  net-tools,
  tree,
  speedtest-cli,
  iperf3,
  xauth,
  dbus-x11,
  mousepad,
  lynx,
  ]
packages_opensuse_default:
  [
  acl,
  zsh,
  git,
  mosh,
  tmux,
  rsync,
  tree
  ]

packages_debian_additional:
  [
    ufw,
    gufw
  ]

packages_kali: [ kali-linux-core, kali-linux-default, kali-desktop-xfce, xorg, xrdp ]


