---
- name: Enable IPv4 fowarding.
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward = 1'

- name: Disable IPv6.
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv6.conf.all.disable_ipv6'
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'


