---
galaxy_info:
  role_name: init
  #namespace: hierophant
  description: etc
  license: etc
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - "all"
  galaxy_tags: []
