---
- name: Deploy on the local machine using Vagrant.
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - deployment/vagrant/debian

- name: Initalize host.
  hosts: vagrant
  roles:
    - setup/init
