---
- name: Deploy Kali Linux on Digital Ocean.
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - setup/ssh_check_local
    - deployment/digitalocean/kali

- name: Initialize Kali Linux.
  hosts: digitalocean
  remote_user: root
  roles:
    - setup/ssh_check_remote
    - setup/init
